name: CD – WebApp (Dev)

on:
  push:
    branches: [dev, development]
    paths: [src/WebApp/**, src/SharedKernel/**]

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          # name: WebApp-${{ github.sha }}
          name: WebApp-latest
          path: ./artifact/WebApp

      - name: Validate artifact content
        run: |
          if [ ! -d "./artifact/WebApp" ] || [ -z "$(ls -A ./artifact/WebApp)" ]; then
            echo "❌ Artifact not found or is empty."
            exit 1
          fi

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: sniffle-webapp-dev
          publish-profile: ${{ secrets.WEBAPP_DEV_PUBLISH_PROFILE }}
          package: ./artifact/WebApp
