name: CD - WebApi (Dev)

on:
  push:
    branches: [dev, development]
    paths: [src/WebApi/**, src/SharedKernel/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Cache NuGet packages
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj', '**/Directory.Build.*', '**/global.json') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ShinySniffle.sln

      # Build project
      - name: Build WebApi
        run: dotnet build src/WebApi/WebApi.csproj --configuration Release --no-restore

      # Publish project
      - name: Publish WebApi
        run: dotnet publish src/WebApi/WebApi.csproj --configuration Release --output ./artifacts/WebApi

      # Zip published project
      - name: Zip published project
        run: zip -r WebApi.zip ./*
        working-directory: ./artifacts/WebApi

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebApi-latest
          # path: ./artifacts/WebApi
          path: ./artifacts/WebApi/WebApi.zip  # If you are zipping the output
          compression-level: 6  #  0 (no compression) to 9 (max)
          if-no-files-found: error

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev

    env:
      ARTIFACT_NAME: WebApi-latest
      ARTIFACT_PATH: ./artifacts/WebApi
      ARTIFACT_ZIP: ./artifacts/WebApi/WebApi.zip  # If you are zipping the output

    steps:
      # Checkout source code (For Vendoring)
      - name: Checkout source code
        uses: actions/checkout@v4

      # Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

      # Validate artifact content
      - name: Validate artifact content
        # run: |
        #   if [ ! -d "${{ env.ARTIFACT_PATH }}" ] || [ -z "$(ls -A ${{ env.ARTIFACT_PATH }})" ]; then
        #     echo "❌ Artifact not found or is empty."
        #     exit 1
        #   fi
        run: |
          if [ ! -f "${{ env.ARTIFACT_ZIP }}" ]; then
            echo "❌ WebApi.zip not found!"
            exit 1
          fi

      # Deploy to Azure WebApp
      - name: Deploy to Azure WebApp
        # uses: azure/webapps-deploy@v2
        uses: ./.github/actions/webapps-deploy/3.0.6
        with:
          app-name: sniffle-webapi-dev
          publish-profile: ${{ secrets.WEBAPI_DEV_PUBLISH_PROFILE }}
          # package: ${{ env.ARTIFACT_PATH }}
          package: ${{ env.ARTIFACT_ZIP }}  # If you are zipping the output

  deploy-stg:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: stg

    env:
      ARTIFACT_NAME: WebApi-latest
      ARTIFACT_PATH: ./artifacts/WebApi
      ARTIFACT_ZIP: ./artifacts/WebApi/WebApi.zip  # If you are zipping the output

    steps:
      # Checkout source code (For Vendoring)
      - name: Checkout source code
        uses: actions/checkout@v4

      # Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

      # Validate artifact content
      - name: Validate artifact content
        # run: |
        #   if [ ! -d "${{ env.ARTIFACT_PATH }}" ] || [ -z "$(ls -A ${{ env.ARTIFACT_PATH }})" ]; then
        #     echo "❌ Artifact not found or is empty."
        #     exit 1
        #   fi
        run: |
          if [ ! -f "${{ env.ARTIFACT_ZIP }}" ]; then
            echo "❌ WebApi.zip not found!"
            exit 1
          fi

      # Deploy to Azure WebApp
      - name: Deploy to Azure WebApp
        # uses: azure/webapps-deploy@v2
        uses: ./.github/actions/webapps-deploy/3.0.6
        with:
          app-name: sniffle-webapi-stg
          publish-profile: ${{ secrets.WEBAPI_STG_PUBLISH_PROFILE }}
          # package: ${{ env.ARTIFACT_PATH }}
          package: ${{ env.ARTIFACT_ZIP }}  # If you are zipping the output
